# Linear Algebra for Machine Learning - Deep Dive

Comprehensive guide to linear algebra concepts essential for understanding machine learning algorithms. This is the mathematical foundation of ML.

## Table of Contents

- [Introduction](#introduction)
- [Tensors](#tensors)
- [Vectors](#vectors)
- [Matrices](#matrices)
- [Matrix Operations](#matrix-operations)
- [Solving Systems of Linear Equations](#solving-systems-of-linear-equations)
  - [Gaussian Elimination (Row Reduction)](#gaussian-elimination-row-reduction)
  - [Solving Ax = 0 (Homogeneous System)](#solving-ax--0-homogeneous-system)
  - [Solving Ax = b (Non-homogeneous System)](#solving-ax--b-non-homogeneous-system)
- [Column Space and Nullspace](#column-space-and-nullspace)
  - [Column Space (Range)](#column-space-range)
  - [Nullspace (Kernel)](#nullspace-kernel)
- [The Four Fundamental Subspaces](#the-four-fundamental-subspaces)
- [Linear Transformations](#linear-transformations)
- [Eigenvalues and Eigenvectors](#eigenvalues-and-eigenvectors)
- [Determinants](#determinants)
  - [What is a Determinant?](#what-is-a-determinant)
  - [Computing Determinants](#computing-determinants)
  - [Properties of Determinants](#properties-of-determinants)
  - [Cofactor Expansion](#cofactor-expansion)
  - [Cramer's Rule](#cramers-rule)
- [Diagonalization](#diagonalization)
  - [What is Diagonalization?](#what-is-diagonalization)
  - [Diagonalization Process](#diagonalization-process)
  - [Powers of A](#powers-of-a)
- [Matrix Exponentials](#matrix-exponentials)
  - [What is exp(At)?](#what-is-expat)
  - [Computing Matrix Exponential](#computing-matrix-exponential)
  - [Solving Differential Equations](#solving-differential-equations)
- [Matrix Decompositions](#matrix-decompositions)
  - [Eigendecomposition](#1-eigendecomposition)
  - [Singular Value Decomposition (SVD)](#2-singular-value-decomposition-svd)
  - [QR Decomposition](#3-qr-decomposition)
- [Pseudoinverse (Moore-Penrose Inverse)](#pseudoinverse-moore-penrose-inverse)
  - [What is a Pseudoinverse?](#what-is-a-pseudoinverse)
  - [Computing Pseudoinverse](#computing-pseudoinverse)
  - [Left and Right Inverses](#left-and-right-inverses)
- [Positive Definite Matrices](#positive-definite-matrices)
  - [What are Positive Definite Matrices?](#what-are-positive-definite-matrices)
  - [Properties and Applications](#properties-and-applications)
  - [Positive Semidefinite Matrices](#positive-semidefinite-matrices)
  - [Cholesky Decomposition](#cholesky-decomposition)
- [Complex Matrices and Fast Fourier Transform](#complex-matrices-and-fast-fourier-transform)
  - [Complex Matrices](#complex-matrices)
  - [Fast Fourier Transform (FFT)](#fast-fourier-transform-fft)
  - [FFT in Machine Learning](#fft-in-machine-learning)
- [Computational Math in Practice](#computational-math-in-practice)
- [Applications in ML](#applications-in-ml)
- [Practice Exercises](#practice-exercises)

---

## Introduction

### Why Linear Algebra is Critical for ML

Linear algebra is the **language of machine learning**. Almost every ML algorithm uses linear algebra:

- **Neural Networks**: Matrix multiplications for forward/backward propagation
- **PCA**: Dimensionality reduction using eigenvectors
- **SVM**: Support vectors and hyperplanes
- **Linear Regression**: Solving systems of equations
- **Recommendation Systems**: Matrix factorization
- **Image Processing**: Convolutions as matrix operations

### What You'll Learn

- Vector operations and properties
- Matrix operations and their meanings
- Linear transformations and their geometric intuition
- Eigenvalues/eigenvectors and their importance
- Matrix decompositions (SVD, eigendecomposition)
- How these concepts apply to ML algorithms

---

## Introduction


### Why Linear Algebra is Critical for ML

Linear algebra is the **language of machine learning**. Almost every ML algorithm uses linear algebra:

- **Neural Networks**: Matrix multiplications for forward/backward propagation
- **PCA**: Dimensionality reduction using eigenvectors
- **SVM**: Support vectors and hyperplanes
- **Linear Regression**: Solving systems of equations
- **Recommendation Systems**: Matrix factorization
- **Image Processing**: Convolutions as matrix operations

### What You'll Learn

- Vector operations and properties
- Matrix operations and their meanings
- Linear transformations and their geometric intuition
- Eigenvalues/eigenvectors and their importance
- Matrix decompositions (SVD, eigendecomposition)
- How these concepts apply to ML algorithms


## Tensors

### What are Tensors?

A **tensor** is a generalization of scalars, vectors, and matrices to higher dimensions. In machine learning, tensors are fundamental data structures used in deep learning frameworks like TensorFlow and PyTorch.

### Tensor Dimensions

**0D Tensor (Scalar)**
- A single number
- Shape: `()`
- Example: `5`, `3.14`



In [2]:
import numpy as np


# 0D tensor (Scaler)
scaler = np.array(42)
print(f'Scaler: {scaler}')
print(f'Shape: {scaler.shape}')  # ()
print(f'Dimentions: {scaler.ndim}')  # 0

Scaler: 42
Shape: ()
Dimentions: 0


**1D Tensor (Vector)**
- An array of numbers
- Shape: `(n,)`
- Example: `[1, 2, 3, 4]`

In [3]:
# 1D tensor (vector)
vector = np.array([1,2,3,4])
print(f'Vector: {vector}')
print(f'Shpae: {vector.shape}') # (4,)
print(f'Dimentions: {vector.ndim}') # 1

Vector: [1 2 3 4]
Shpae: (4,)
Dimentions: 1


**2D Tensor (Matrix)**
- A 2D array of numbers
- Shape: `(m, n)`
- Example: `[[1, 2], [3, 4]]`

In [4]:
# 2D tensor (matrix)
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print(f'Matrix:\n{matrix}')
print(f'Shape: {matrix.shape}') # (3, 3)
print(f'Dimensions: {matrix.ndim}') # 2

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Dimensions: 2


**3D Tensor**
- A 3D array
- Shape: `(d, m, n)`
- Example: Batch of images, RGB images

In [5]:
# 3D tensor (e.g., batch of 2D images)
tensor_3d = np.array([[[1,2], [3,4]],
                       [[5,6], [7,8]]])
print(f'3d Tensor:\n{tensor_3d}')
print(f'Shape: {tensor_3d.shape}') # (2, 2, 2)
print(f'Dimensions: {tensor_3d.ndim}') # 3

3d Tensor:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)
Dimensions: 3


**4D Tensor**
- Common in deep learning for batches of images
- Shape: `(batch, height, width, channels)`
- Example: Batch of RGB images: `(32, 224, 224, 3)`

In [6]:
# 4D tensor (e.g., batch of RGB images)
# Shape: (batch_size, height, width, channels)

batch_images = np.random.rand(32, 224, 224, 3)
print(f'4d Tensor (Batch of Images) Shape: {batch_images.shape}') # (32, 224, 224, 3)
print(f'Dimentions: {batch_images.ndim}') # 4
print(f'Total Elements: {batch_images.size}') # 32*224*224*3

4d Tensor (Batch of Images) Shape: (32, 224, 224, 3)
Dimentions: 4
Total Elements: 4816896


**5D Tensor**
- Used for video data or 3D medical images
- Shape: `(batch, time, height, width, channels)`

In [ ]:
# 5D tensor (e.g., video frames) 
# Shape: (batch, frames, height, width, channels)

video = np.random.rand(8, 16, 224, 224, 3)
print(f'5D Tensor (Video) Shape: {video.shape}') # (8, 16, 224, 224, 3)
print(f'5D Tensor (Video) Dimentions: {video.ndim}') # 5
print(f'5D Tensor (Video) Total Elements: {video.size}') # 8

5D Tensor (Video) Shape: (8, 16, 224, 224, 3)
5D Tensor (Video) Dimentions: 5
5D Tensor (Video) Total Elements: 19267584


In [ ]:
k