# 🧮 NumPy কী?

**NumPy** হলো Python-এর একটি মৌলিক লাইব্রেরি, যা **scientific computing (বৈজ্ঞানিক গণনা)**-এর জন্য ব্যবহৃত হয়।  
এটি এমন একটি লাইব্রেরি যা **multidimensional array object (একাধিক মাত্রার অ্যারে অবজেক্ট)**, কিছু **derived object** (যেমন masked array, matrix ইত্যাদি) এবং বিভিন্ন ধরনের **দ্রুতগতির অ্যারে অপারেশন** করার ফাংশন সরবরাহ করে।  

### ✳️ NumPy যা করতে পারে:
- Mathematical এবং Logical operation  
- Shape পরিবর্তন (Shape manipulation)  
- Sorting ও Selecting  
- Input/Output (I/O) অপারেশন  
- Discrete Fourier Transform  
- Basic Linear Algebra (যেমন: ম্যাট্রিক্সের যোগ-বিয়োগ-গুণ)  
- Statistical operations (গড়, variance ইত্যাদি)  
- Random simulation এবং আরও অনেক কিছু  

---

## 🧱 NumPy-এর মূল অংশ – `ndarray` অবজেক্ট

NumPy-এর সবচেয়ে গুরুত্বপূর্ণ অংশ হলো **`ndarray` object**,  
যা **n-dimensional homogeneous data array** ধারণ করে।  
এর মানে হলো, এটি একাধিক মাত্রার অ্যারে রাখে এবং সব উপাদান (elements) একই ডেটা টাইপের হয় (যেমন সবগুলো `int` বা সবগুলো `float`)।

---

## ⚖️ NumPy Arrays বনাম Python Sequences

| বিষয় | NumPy Array | Python List / Sequence |
|------|--------------|------------------------|
| **আকার (Size)** | নির্দিষ্ট (fixed) | পরিবর্তনযোগ্য (grow/shrink dynamically) |
| **ডেটা টাইপ** | সব উপাদান একই টাইপের | ভিন্ন ভিন্ন টাইপের হতে পারে |
| **পারফরম্যান্স** | খুব দ্রুত (C-এ লেখা) | তুলনামূলক ধীর |
| **অপারেশন** | গাণিতিক ও বৈজ্ঞানিক কাজে দক্ষ | তেমন দক্ষ নয় |

🧩 NumPy array তৈরি করার সময়ই এর আকার নির্ধারিত হয়।  
তুমি যদি আকার পরিবর্তন করো, তাহলে পুরনো অ্যারে ডিলিট হয়ে নতুন একটি তৈরি হয়।

---

## ⚙️ কেন NumPy ব্যবহার করা হয়?

NumPy ব্যবহার করলে বড় পরিসরের ডেটার ওপর জটিল গাণিতিক বা বৈজ্ঞানিক অপারেশনগুলো  
অনেক সহজ ও দ্রুত করা যায়।  
Python-এর সাধারণ `list` বা `tuple` দিয়ে করলে কোড বেশি লাগে এবং গতি কম হয়।

---

## 🌍 NumPy-এর গুরুত্ব

বেশিরভাগ বৈজ্ঞানিক ও গাণিতিক Python লাইব্রেরি (যেমন **Pandas**, **SciPy**, **TensorFlow**)  
সবই **NumPy array**-এর ওপর ভিত্তি করে তৈরি।  

তারা ইনপুট হিসেবে Python list নিতে পারে,  
কিন্তু প্রক্রিয়াকরণের আগে সেটাকে NumPy array-এ রূপান্তর করে নেয়।  
আউটপুট হিসেবেও সাধারণত NumPy array ফেরত দেয়।

---

## 💡 উদাহরণ


```

In [1]:

import numpy as np

# 1D array তৈরি
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)

# কিছু অপারেশন
print("Mean:", np.mean(arr))
print("Standard Deviation:", np.std(arr))
print("Square:", np.square(arr))

Array: [1 2 3 4 5]
Mean: 3.0
Standard Deviation: 1.4142135623730951
Square: [ 1  4  9 16 25]



## 🔹 1️⃣ 1D Array (One-Dimensional Array)

> এক মাত্রিক অ্যারে হলো একটি সরল **list**-এর মতো —  
> যেখানে উপাদানগুলো একের পর এক থাকে, যেমন `[1, 2, 3, 4, 5]`।

🧠 ব্যাখ্যা:
- এখানে ndim = 1 মানে এটি এক-মাত্রিক অ্যারে।
- shape = (5,) মানে অ্যারেতে ৫টি উপাদান আছে, এক লাইনেই।


In [2]:

import numpy as np

# 1D array তৈরি
arr1 = np.array([10, 20, 30, 40, 50])
print("1D Array:\n", arr1)
print("Dimension:", arr1.ndim)
print("Shape:", arr1.shape)

1D Array:
 [10 20 30 40 50]
Dimension: 1
Shape: (5,)


## 2️⃣ 2D Array (Two-Dimensional Array)

- দুই মাত্রিক অ্যারে মানে একাধিক সারি (rows) ও কলাম (columns) —
- যেমন একটা ম্যাট্রিক্স বা টেবিল।

🧠 ব্যাখ্যা:

- ndim = 2 মানে এটি দুই মাত্রিক।
- shape = (3, 3) মানে ৩টি সারি ও ৩টি কলাম আছে।

In [3]:
# 2D array তৈরি ---can call it matrix
arr2 = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print('2D array:\n', arr2)
print('Dimention: ', arr2.ndim)
print('Shape: ', arr2.shape)

2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimention:  2
Shape:  (3, 3)



## 🔹 3️⃣ 3D Array (Three-Dimensional Array)

- তিন মাত্রিক অ্যারে হলো অ্যারেগুলোর স্তূপ (stack) —
- অর্থাৎ একাধিক 2D ম্যাট্রিক্স একসাথে রাখা।
- একে সহজভাবে ভাবা যায়, যেন একাধিক পাতার নোটবুক 📘,
- প্রতিটি পাতাই একটি 2D array।

🧠 ব্যাখ্যা:

- এখানে ndim = 3 → তিন মাত্রিক।
- shape = (2, 2, 3) মানে:
- ২টা 2D ম্যাট্রিক্স (অর্থাৎ ২টি “layer”)
- প্রতিটি ম্যাট্রিক্সে ২টি সারি ও 3টি কলাম।

In [5]:
# 3D array তৈরি ---- can call it tensor
arr3 = np.array([[[1,2,3],
                [4,5,6]],
                [[7,8,9],
                [10,11,12]]])
print('3D array:\n', arr3)
print('Dimension: ', arr3.ndim)
print('Shape: ', arr3.shape)

3D array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Dimension:  3
Shape:  (2, 2, 3)


## `dtype` (Data Type in NumPy)
- NumPy-তে dtype মানে Data Type।
- এটি বলে দেয় একটি NumPy array-এর প্রতিটি উপাদানের ডেটার ধরন কী — যেমন integer, float, string ইত্যাদি।

|         `dtype`        | মানে           | বর্ণনা                   |
| :--------------------: | :------------- | :----------------------- |
|   `int32` বা `int64`   | Integer        | পূর্ণ সংখ্যা             |
| `float32` বা `float64` | Floating point | দশমিকসহ সংখ্যা           |
|         `bool`         | Boolean        | True বা False মান        |
|        `complex`       | Complex Number | বাস্তব ও কাল্পনিক সংখ্যা |
|      `str` বা `<U`     | Unicode string | টেক্সট ডেটা              |


In [6]:
# dtype

a = np.array([1,2,3,4], dtype='int')
b = np.array([1,2,3,4,5], dtype='float')
c = np.array([1,2,3,4,5], dtype='complex')

print(a, a.dtype)
print(b, b.dtype)
print(c, c.dtype)

[1 2 3 4] int64
[1. 2. 3. 4. 5.] float64
[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j] complex128


## 🔢 np.arange() — (NumPy Range Function)

 - np.arange() হলো NumPy-এর একটি ফাংশন,
 - যা নির্দিষ্ট range (পরিসীমা) অনুযায়ী সমান ব্যবধানের সংখ্যা তৈরি করে।
- এক কথায় — এটি Python-এর range() ফাংশনের মতো,
- কিন্তু NumPy array আকারে আউটপুট দেয়

    ```
    np.arange(start, stop, step, dtype=None)
    ```
| Parameter | ব্যাখ্যা                             |
| :-------- | :----------------------------------- |
| `start`   | শুরু মান (ডিফল্ট 0)                  |
| `stop`    | শেষ মান (এই মানটি অন্তর্ভুক্ত হয় না) |
| `step`    | প্রতিটি মানের ব্যবধান (ডিফল্ট 1)     |
| `dtype`   | আউটপুটের ডেটাটাইপ (ঐচ্ছিক)           |


In [9]:
import numpy as np

# 🧾 উদাহরণ ১ — সাধারণ ব্যবহার:
arr = np.arange(10)  # 0 থেকে 9 পর্যন্ত সংখ্যা
print("Array:", arr)

# 🧾 উদাহরণ ২ — Start, Stop, Step সহ:
arr2 = np.arange(1, 10, 2)  # 1 থেকে 9 পর্যন্ত বিজোড় সংখ্যা
print("Array with step:", arr2)

# 🧾 উদাহরণ ৩ — Float মান সহ:
arr3 = np.arange(0.5, 5.5, 1.0)  # 0.5 থেকে 5.5 পর্যন্ত 1.0 করে বৃদ্ধি
print("Float array:", arr3)

# ⚙️ dtype নির্দিষ্ট করা:

arr4 = np.arange(5, 10, 2, dtype='float') # 5 থেকে 10 পর্যন্ত 3 করে বৃদ্ধি, float টাইপ
print("Array with specific dtype:", arr4)

Array: [0 1 2 3 4 5 6 7 8 9]
Array with step: [1 3 5 7 9]
Float array: [0.5 1.5 2.5 3.5 4.5]
Array with specific dtype: [5. 7. 9.]


### সংক্ষেপে মনে রাখো:
✅ `np.arange(start, stop, step)`
- Start থেকে Stop পর্যন্ত Step ব্যবধানে সংখ্যা তৈরি করে
- Stop মানটি অন্তর্ভুক্ত হয় না
- আউটপুট দেয় NumPy array

## 🔄 reshape() — (Array-এর আকার পরিবর্তন)
`reshape()` ফাংশন ব্যবহার করে আমরা কোনো NumPy array-এর `shape বা dimension` পরিবর্তন করতে পারি,
- কিন্তু ডেটা অপরিবর্তিত থাকে।
- অর্থাৎ — একই ডেটা, নতুন আকারে সাজানো হয়।
```
array.reshape(new_shape)
```

In [10]:
import numpy as np

# 🧾 উদাহরণ ১ — 1D → 2D
arr = np.arange(6) # 0 থেকে 5 পর্যন্ত সংখ্যা
print("Original 1D array:", arr)

new_arr = arr.reshape(2, 3) # 2 rows এবং 3 columns
print('Reshaped to 2D array:\n', new_arr)

Original 1D array: [0 1 2 3 4 5]
Reshaped to 2D array:
 [[0 1 2]
 [3 4 5]]


In [11]:
# 🧾 উদাহরণ ২ — 1D → 3D
arr = np.arange(8) # 0 থেকে 7 পর্যন্ত সংখ্যা
print("Original 1D array:", arr)

reshaped = arr.reshape(2, 2, 2) # 2 blocks, 2 rows, 2 columns
print('Reshaped to 3D array:\n', reshaped)

Original 1D array: [0 1 2 3 4 5 6 7]
Reshaped to 3D array:
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [12]:
# 🧾 উদাহরণ ৩ — স্বয়ংক্রিয় dimension (Auto detect with -1)

arr = np.arange(12) # 0 থেকে 11 পর্যন্ত সংখ্যা
print("Original 1D array:", arr)

reshaped_auto = arr.reshape(3, -1) # 3 rows এবং auto-detect column
print('Reshaped with auto-detect:\n', reshaped_auto)

Original 1D array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped with auto-detect:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


🔹 **এখানে `-1` মানে “NumPy নিজে বুঝে নেবে কত কলাম দরকার”।**

### ⚠️ গুরুত্বপূর্ণ নিয়ম:

- ✅ মোট উপাদানের সংখ্যা (elements) একই থাকতে হবে
- যেমন, arr-এর দৈর্ঘ্য যদি 8 হয়,
- তাহলে (2, 4), (4, 2), (2, 2, 2) — এসব বৈধ,
- কিন্তু (3, 3) অবৈধ কারণ 9 ≠ 8।

## 🧩 .reshape() ও .shape এর পার্থক্য
| বিষয়        | `.reshape()`               | `.shape`              |
| :---------- | :------------------------- | :-------------------- |
| কাজ         | Array-এর আকার পরিবর্তন করে | বর্তমান আকার জানায়    |
| আউটপুট      | নতুন array রিটার্ন করে     | Tuple আকারে shape দেয় |
| পরিবর্তন হয় | না, নতুন কপি তৈরি হয়       | না, শুধু তথ্য দেয়     |


In [ ]:
# examples with reshape and shape
arr = np.arange(1, 11).reshape(2, 5) # 1 থেকে 10 পর্যন্ত সংখ্যা, 2 rows এবং 5 columns
print("Reshaped array:\n", arr) 
print("Shape:", arr.shape) 

Reshaped array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Shape: (2, 5)
